### ISSUE TITLE
How to use serviceWorkerParam and serviceWorkerPath?

### ISSUE THREAD

**Issue by classicPintus** [OneSignal/onesignal-ngx#11]
Hello,
I'm not understanding how to use serviceWorkerParam and serviceWorkerPath in combination with this library.

Please Can you provide a little example?

Thank you

**Comment by rgomezp** [comment]
Howdy Gavino,
Thanks for your patience.

The params are passed as initialization options:

```js
this.oneSignal.init({
   appId: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
   serviceWorkerParam: '<path scope>',
   serviceWorkerPath: '<path>'
}).then(() => {
  // do other stuff
});
```

Hope that helps!

**Comment by dylanvdmerwe** [comment]
It would be amazing if you could provide an example. What would a scope look like?

**Comment by rgomezp** [comment]
@dylanvdmerwe ,
It would be something like:
```js
this.oneSignal.init({
   appId: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
   serviceWorkerParam: {
      scope: "/push"
   },
   serviceWorkerPath: '<path>'
}).then(() => {
  // do other stuff
});
```

You can learn more [here](https://documentation.onesignal.com/docs/onesignal-service-worker-faq#customizing-your-service-worker-integration).
