### ISSUE TITLE
Error installing from NPM

### ISSUE THREAD

**Issue by andy008** [OneSignal/onesignal-ngx#15]
Using:-

npm install --save onesignal-ngx

results in:-

Found: @angular/common@13.2.7
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~13.2.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^11.0.9" from onesignal-ngx@1.0.0
npm ERR! node_modules/onesignal-ngx
npm ERR!   onesignal-ngx@"*" from the root project

**Comment by matiasAS** [comment]
@gdeglin  @leemunroe @leemunroe @jmadler @jkasten2 

Hello, I have the same error and I need an urgent solution.

npm ERR! Found: @angular/common@13.2.7
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~13.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^11.0.9" from onesignal-ngx@1.0.0
npm ERR! node_modules/onesignal-ngx
npm ERR!   onesignal-ngx@"*" from the root project

**Comment by rgomezp** [comment]
Thanks for your patience.

The problem here is that the package has a peer-dependency of Angular 11 which we downgraded to from 12 for backwards compatibility.

We will need to update this to be more lenient, and figure out if and where any compatibility breaks.

**Comment by matiasAS** [comment]
Hello @rgomezp  and how much will be available for angular 13+?, speak spanish?
