### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jonatan280792** [OneSignal/onesignal-ngx#23]
### What happened?

Error installing onegisnal-ngx package, using angular/cli version 7.0.4

### What browsers are you seeing the problem on?

Firefox, Chrome (Chromium), Microsoft Edge

### What operating system are you running?

Windows 11 Home

### Steps to reproduce?

```Markdown
1. Install angular version 7.0.4.
2. Install npm onesignal-ngx
3. Build proyect "ng serve"
4. Error in browser
![image](https://user-images.githubusercontent.com/54013509/193499139-deca7f35-fb86-476b-9732-7e1e695f55ad.png)
```

### What did you expect to happen?

Error installing onegisnal-ngx package, using angular/cli version 7.0.4

![image](https://user-images.githubusercontent.com/54013509/193499139-deca7f35-fb86-476b-9732-7e1e695f55ad.png)
![image](https://user-images.githubusercontent.com/54013509/193499269-3e78e8dd-3a50-4e7f-b3ef-faf49e31b71c.png)

**Comment by iAmWillShepherd** [comment]
👋🏽 @jonatan280792 

Would you mind updating the title of your issue to "[Bug] Plugin fails to build with Angular 7"?

**Comment by iAmWillShepherd** [comment]
@jonatan280792 after some conversation with the team, I've learned that our plugin doesn't support Angular 7, and there is no intention to support Angular 7 at this time.
