### ISSUE TITLE
[Question]: Do you guys have any example/sample Angular projects I could use to troubleshoot?

### ISSUE THREAD

**Issue by hiddenkirby** [OneSignal/onesignal-ngx#26]
### How can we help?

I have a PWA-enabled Angular v15 app. I'm wondering if you guys might have something i could maybe clone, put my appId in , and then use to compare with... my failing configuration.

It doesn't have to be Angular 15 as much as something that is using both ngsw-worker.js and onesignal successfully together.

**Comment by hiddenkirby** [comment]
Ok, I believe this issue to be related to the Brave Browser and https://github.com/OneSignal/OneSignal-Website-SDK/issues/526#issuecomment-1002344500

**Comment by jkasten2** [comment]
Sorry for not getting to your issue, please open an new issue if the new 2.0.0 does not fix your issue. Or as you noted, it may be an issue with OneSignal/OneSignal-Website-SDK and continue following that issue.
